apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-fezi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-fezi
    app.kubernetes.io/part-of: tkrw-pr712-0075-0042-app
  name: devfile-sample-fezi
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-fezi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-fezi
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0042-tenant/tkrw-pr712-0075-0042-app/devfile-sample-fezi@sha256:fe7b0085bf4a4a88bc25561a90b7d4af8604e39985528a809bb94d2173a4f107
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
